In [1]:
import pandas as pd
import numpy as np

inicio = int(input('Introduce el año inicial: '))
fin = int(input('Introduce el año final: '))
ventas = {}
for i in range(inicio, fin+1):
    ventas[i] = float(input('Introduce las ventas del año ' + str(i) +': '))
ventas = pd.Series(ventas)
print('Ventas\n', ventas)
print('Ventas con descuento\n', ventas*0.9)


Introduce el año inicial: 1
Introduce el año final: 2
Introduce las ventas del año 1: 3
Introduce las ventas del año 2: 4
Ventas
 1    3.0
2    4.0
dtype: float64
Ventas con descuento
 1    2.7
2    3.6
dtype: float64


In [8]:

one= np.array([2,3,4])
print(one)
print(type(one))
print(one.ndim)

[2 3 4]
<class 'numpy.ndarray'>
1


In [9]:
dos= np.array([[2,3,4],[6,7,8]])
print(dos)
print(type(dos))
print(dos.ndim)

[[2 3 4]
 [6 7 8]]
<class 'numpy.ndarray'>
2


In [10]:
tres= np.array([[[1,2,3],[11,-2,-3]],[[4,5,6],[-4,-5,-6]]])
print(tres)
print(type(tres))
print(tres.ndim)

[[[ 1  2  3]
  [11 -2 -3]]

 [[ 4  5  6]
  [-4 -5 -6]]]
<class 'numpy.ndarray'>
3


In [11]:
print(tres[0,0,0])

1


In [12]:
print(tres[1,1])

[-4 -5 -6]


In [13]:
tt= np.array([[[1,2,3],[11,-2,-3]],[[4,5,6],[-4,-5,-6]]])
print(tt[0,1])

[11 -2 -3]


In [14]:
dosarray= np.array([[1,2,3],[4,5,6]])
for x in dosarray:
    print(x)

[1 2 3]
[4 5 6]


In [15]:
for y in dosarray:
    for k in y:
        print(k)

1
2
3
4
5
6


In [16]:
g= np.array([[[1,2,3],[11,-2,-3]],[[4,5,6],[-4,-5,-6]]])
for i in g:
    for x in i:
        for j in x:
            print(j)

1
2
3
11
-2
-3
4
5
6
-4
-5
-6


In [17]:
zeroarray=np.zeros(10)
print(zeroarray)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [18]:
zeroarray= zeroarray.astype(int)
print(zeroarray)
                        

[0 0 0 0 0 0 0 0 0 0]


In [19]:
onesArray= np.ones(10)
print(onesArray)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [20]:
prefillarray= np.full(1,4)
print(prefillarray)

[4]


In [21]:
matrix= np.array([[1,2,3],[4,5,6]])
print(matrix)
print()
print(matrix+2)

[[1 2 3]
 [4 5 6]]

[[3 4 5]
 [6 7 8]]


In [22]:
print(matrix-2)

[[-1  0  1]
 [ 2  3  4]]


In [23]:
print(matrix+2)

[[3 4 5]
 [6 7 8]]


In [24]:
print(matrix/2)
print(matrix)

[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[1 2 3]
 [4 5 6]]


In [25]:
print(matrix**2)

[[ 1  4  9]
 [16 25 36]]


In [26]:
numpy.transponer 

NameError: name 'numpy' is not defined

In [27]:

print(matrix.T)

[[1 4]
 [2 5]
 [3 6]]


In [28]:
matrix11=np.array([[1,2,3],[4,5,6]])
print(matrix11)

[[1 2 3]
 [4 5 6]]


In [29]:
matrix22=np.array([[-1,-2,-3],[-4,-5,-6]])
print(matrix22)

[[-1 -2 -3]
 [-4 -5 -6]]


In [30]:
print(matrix11 + matrix22)

[[0 0 0]
 [0 0 0]]


In [31]:
print(matrix11 - matrix22)

[[ 2  4  6]
 [ 8 10 12]]


In [32]:
print(matrix11 / matrix22)

[[-1. -1. -1.]
 [-1. -1. -1.]]


In [33]:
print(matrix11 // matrix22)

[[-1 -1 -1]
 [-1 -1 -1]]


In [34]:
matrixk=np.array([[1,2,3],[4,5,6],[0,0,0]])
print(matrixk)

[[1 2 3]
 [4 5 6]
 [0 0 0]]


In [35]:
matrixl=np.array([[-1,-2,-3],[-4,-5,-6],[0,0,0]])
print(matrixl)

[[-1 -2 -3]
 [-4 -5 -6]
 [ 0  0  0]]


In [36]:
print(matrixl,matrixk)

[[-1 -2 -3]
 [-4 -5 -6]
 [ 0  0  0]] [[1 2 3]
 [4 5 6]
 [0 0 0]]


In [37]:
np.matmul(matrixk,matrixl)

array([[ -9, -12, -15],
       [-24, -33, -42],
       [  0,   0,   0]])

In [38]:
a= np.array([1,2])
b= np.array([3,4])
resulatado= np.dot(a,b)
print(resulatado)

11


In [48]:
minimo = np.array([10,4,5])
np.min(minimo)

4

In [49]:
np.sum(minimo)

19

In [50]:
print(sum(minimo))

19


In [51]:
np.max(minimo)

10

In [52]:
print(max(minimo))

10


In [53]:
np.mean(minimo)

6.333333333333333

In [55]:
np.std(minimo)

2.6246692913372702

In [57]:
desviacion= np.array([6,2,3,1])
print(desviacion)
np.std(desviacion)

[6 2 3 1]


1.8708286933869707